export const STAT_LABELS = {
    airDamage: "Air Damage",
    airDefence: "Air Defence",
    airMainAttackDamage: "Air Main Attack Damage",
    airSpellDamage: "Air Spell Damage",
    agilityRequirement: "Agility Req.",
    attackSpeed: "Attack Speed",
    averageDps: "Average DPS",
    baseAirDamage: "Air Damage",
    baseDamage: "Neutral Damage",
    baseEarthDamage: "Earth Damage",
    baseFireDamage: "Fire Damage",
    baseHealth: "Health",
    baseThunderDamage: "Thunder Damage",
    baseWaterDamage: "Water Damage",
    combatExperience: "XP Bonus",
    damageFromMobs: "Damage From Mobs",
    defenceRequirement: "Defence Req.",
    dexterityRequirement: "Dexterity Req.",
    durabilityModifier: "Durability",
    earthDamage: "Earth Damage",
    earthDefence: "Earth Defence",
    earthSpellDamage: "Earth Spell Damage",
    elementalDamage: "Elemental Damage",
    elementalDefence: "Elemental Defence",
    elementalSpellDamage: "Elemental Spell Damage",
    fireDamage: "Fire Damage",
    fireDefence: "Fire Defence",
    fireSpellDamage: "Fire Spell Damage",
    gatherSpeed: "Gather Speed",
    gatherXpBonus: "Gather XP Bonus",
    gatheringExperience: "Gathering Experience",
    gatheringSpeed: "Gathering Speed",
    healthRegen: "Health Regen",
    healthRegenRaw: "Health Regen Raw",
    intelligenceRequirement: "Intelligence Req.",
    jumpHeight: "Jump Height",
    lifeSteal: "Life Steal",
    lootBonus: "Loot Bonus",
    lootQuality: "Loot Quality",
    mainAttackDamage: "Main Attack Damage",
    mainAttackRange: "Main Attack Range",
    manaRegen: "Mana Regen",
    manaSteal: "Mana Steal",
    poison: "Poison",
    raw1stSpellCost: "Raw 1st Spell Cost",
    raw2ndSpellCost: "Raw 2nd Spell Cost",
    raw3rdSpellCost: "Raw 3rd Spell Cost",
    raw4thSpellCost: "Raw 4th Spell Cost",
    "1stSpellCost": "1st Spell Cost",
    "2ndSpellCost": "2nd Spell Cost",
    "3rdSpellCost": "3rd Spell Cost",
    "4thSpellCost": "4th Spell Cost",
    rawAgility: "Raw Agility",
    rawAirMainAttackDamage: "Raw Air Main Attack Damage",
    rawAirSpellDamage: "Raw Air Spell Damage",
    rawAttackSpeed: "Raw Attack Speed",
    rawDefence: "Raw Defence",
    rawDexterity: "Raw Dexterity",
    rawEarthSpellDamage: "Raw Earth Spell Damage",
    rawElementalDamage: "Raw Elemental Damage",
    rawElementalMainAttackDamage: "Raw Elemental Main Attack",
    rawElementalSpellDamage: "Raw Elemental Spell Damage",
    rawFireMainAttackDamage: "Raw Fire Main Attack Damage",
    rawFireSpellDamage: "Raw Fire Spell Damage",
    rawHealth: "Raw Health",
    rawIntelligence: "Raw Intelligence",
    rawMainAttackDamage: "Raw Main Attack Damage",
    rawNeutralSpellDamage: "Raw Neutral Spell Damage",
    rawSpellDamage: "Raw Spell Damage",
    rawStrength: "Raw Strength",
    rawThunderDamage: "Raw Thunder Damage",
    rawThunderMainAttackDamage: "Raw Thunder Main Attack Damage",
    rawThunderSpellDamage: "Raw Thunder Spell Damage",
    rawWaterDamage: "Raw Water Damage",
    rawWaterSpellDamage: "Raw Water Spell Damage",
    spellDamage: "Spell Damage",
    sprint: "Sprint",
    sprintRegen: "Sprint Regen",
    stealing: "Stealing",
    strengthRequirement: "Strength Req.",
    thorns: "Thorns",
    thunderDamage: "Thunder Damage",
    thunderDefence: "Thunder Defence",
    thunderMainAttackDamage: "Thunder Main Attack Damage",
    walkSpeed: "Walk Speed",
    waterDamage: "Water Damage",
    waterDefence: "Water Defence",
    waterSpellDamage: "Water Spell Damage",
    xpBonus: "XP Bonus"
};

export const REQUIREMENT_LABELS = {
    agility: "Agility",
    classRequirement: "Class",
    defence: "Defence",
    dexterity: "Dexterity",
    intelligence: "Intelligence",
    level: "Combat Level",
    strength: "Strength"
};

export function titleCase(value) {
    return String(value ?? "")
        .replace(/([a-z])([A-Z])/g, "$1 $2")
        .replace(/[-_]/g, " ")
        .replace(/\b\w/g, (letter) => letter.toUpperCase());
}

export function formatItemLabel(name) {
    return STAT_LABELS[name] ?? REQUIREMENT_LABELS[name] ?? titleCase(name);
}
